### ISSUE TITLE
Does not work on S20 V1.3?

### ISSUE THREAD

**Issue by Shellfishgene** [KmanOz/KmanSonoff#10]
I just installed on my Sonoff S20 socket, the PCB is labelled "S20_EU_V1.3 2017-2-16". It seems to have flashed ok from the Arduino IDE, but when I plug it in nothing happens. The LED does not light up at all, the button does nothing, and it does not connect to Wifi. I filled all the info int the h file correctly.

**Comment by Straeng** [comment]
Hello,
I'm having the same issue. Hardware S20_EU_V1.3 (2017-2-16).

Flashing is OK but then the switch is dead (can re-flash it tho). 
When plugged in nothing happens, no LED, cant use the button.

**Comment by KmanOz** [comment]
What Straeng said 👍
