### ISSUE TITLE
Assign Station name

### ISSUE THREAD

**Issue by MaccaAus** [KmanOz/KmanSonoff#2]
Is it possible to integrate a variable we can change to have a user fixed Station name as opposed to the auto assigned one?

I have 10 ESP's currently running on my network, stuff gets confusing.

**Comment by KmanOz** [comment]
As in SONOFF_XXXXXX do you mean?

**Comment by MaccaAus** [comment]
Yeh make the Sonoff_MacAddress name a variable you could define in the config.h
eg #define WIFI_NAME

**Comment by KmanOz** [comment]
I'll think about it in a future version. Thanks
