### ISSUE TITLE
Sonoff S20 - doesnt work at all

### ISSUE THREAD

**Issue by MrPasty** [KmanOz/KmanSonoff#3]
Hi, 

I flashed this to my Sonoff S20 and it doesnt do anything, no lights, no attempt to connect to network mqtt - I even erased the flash and tried it multiple different ways??

have you tested this on an S20?

Thanks

**Comment by KmanOz** [comment]
Have you checked what type of Flash it has? Sounds like the newer type and you need to program it differently. Sorry I don't have all the details on the page, plenty of other places do though.

**Comment by TribuneX** [comment]
Make sure to use --flash_mode dout e.g. with the esptool.py. I flashed it without setting the right flash mode and it was soft bricked. After flashing it with mode dout, it worked without an issue.
