### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by ralphyX** [KmanOz/KmanSonoff#6]
Hi,

I can't upload to sonoff device. here are the error message from the arduino ide

`In file included from /Users//Downloads/KmanSonoff-master/arduino/KmanSonoff_v1.00sc/KmanSonoff_v1.00sc.ino:1:0:
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:25:38: error: expected class-name before '{' token
   class ConnectJSON : public Connect {
                                      ^
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:29:5: error: 'Connect' does not name a type
     Connect& set_will(String willTopic, ArduinoJson::Internals::JsonPrintable<J>& willMessage, uint8_t willQos, bool willRetain) {
     ^
In file included from /Users/user/Downloads/KmanSonoff-master/arduino/KmanSonoff_v1.00sc/KmanSonoff_v1.00sc.ino:1:0:
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:47:38: error: expected class-name before '{' token
   class PublishJSON : public Publish {
                                      ^
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h: In constructor 'MQTT::PublishJSON::PublishJSON(String, ArduinoJson::Internals::JsonPrintable<TImpl>&)':
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:56:7: error: class 'MQTT::PublishJSON' does not have any field named 'Publish'
       Publish(topic, nullptr, object.measureLength() + 1)
       ^
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:58:7: error: '_payload' was not declared in this scope
       _payload = new uint8_t[_payload_len];
       ^
/Users/user/Documents/Arduino/libraries/pubsubclient-master/src/PubSubClient_JSON.h:58:30: error: '_payload_len' was not declared in this scope
       _payload = new uint8_t[_payload_len];
                              ^
Bibliothek pubsubclient-master in Version 1.99.1 im Ordner: /Users/user/Documents/Arduino/libraries/pubsubclient-master  wird verwendet
Bibliothek ArduinoJson in Version 5.11.2 im Ordner: /Users/user/Documents/Arduino/libraries/ArduinoJson  wird verwendet
Bibliothek EEPROM in Version 1.0 im Ordner: /Users/user/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/EEPROM  wird verwendet
Bibliothek ESP8266WiFi in Version 1.0 im Ordner: /Users/user/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi  wird verwendet
Bibliothek ESP8266mDNS im Ordner: /Users/user/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266mDNS (legacy) wird verwendet
Bibliothek ArduinoOTA in Version 1.0 im Ordner: /Users/user/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ArduinoOTA  wird verwendet
Bibliothek Ticker in Version 1.0 im Ordner: /Users/user/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/Ticker  wird verwendet
exit status 1
Fehler beim Kompilieren für das Board Generic ESP8266 Module.`

**Comment by KmanOz** [comment]
Read the documentation on the Github and follow every step. You are using the wrong library.

**Comment by ralphyX** [comment]
Sorry, but I don't see which librabry should be wrong?

pubsubclient-master 1.99.1 (in the Arduino IDE it is named as PubSubClient(imroy)
ArduinoJson 5.11.2
EEPROM 1.0
ESP8266WiFi 1.0
ESP8266mDNS
ArduinoOTA 1.0
Ticker 1.0
Fehler beim Kompilieren für das Board Generic ESP8266 Module.
