### ISSUE TITLE
Unable to get Si7021 temperature/humidity sensor to work in HA

### ISSUE THREAD

**Issue by saroberts** [KmanOz/KmanSonoff#7]
I have a series of TH10 sensors and the switch works beautifully in Home Assistant.  I also purchased the Si7021 temperature and humidity sensors.  However, I am unable to get them to work.  I have tried a variety of options in the configuration file (e.g. TEMP/WS, DHT11/DHT22) but can't seem to get it to work.  Can you provide any assistance on this particular sensor?

**Comment by KmanOz** [comment]
That's an I2C device and I have no code in the firmware at the moment to support that sorry
